version: '2'

services:

  zookeeper:
    image: docker-registry.dvbern.ch/dockerhub/confluentinc/cp-zookeeper:${CONFLUENT_PLATFORM_VERSION}
    networks:
      - kibon-exchange
    ports:
      - "2181:2181"
    environment:
      TZ: "Europe/Zurich"
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: docker-registry.dvbern.ch/dockerhub/confluentinc/cp-kafka:${CONFLUENT_PLATFORM_VERSION}
    networks:
      - kibon-exchange
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      TZ: "Europe/Zurich"
      KAFKA_LOG_DIRS: "/tmp/logs"
      KAFKA_LOG_RETENTION_HOURS: -1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://${KAFKA_ADDR}:9092
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  schema-registry:
    image: docker-registry.dvbern.ch/dockerhub/confluentinc/cp-schema-registry:${CONFLUENT_PLATFORM_VERSION}
    hostname: schema-registry
    networks:
      - kibon-exchange
    depends_on:
      - zookeeper
      - kafka
    ports:
      - "8081:8081"
    environment:
      TZ: "Europe/Zurich"
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'
      SCHEMA_REGISTRY_AVRO_COMPATIBILITY_LEVEL: 'full_transitive'
      SCHEMA_REGISTRY_DEBUG: 'true'

  db:
    image: docker-registry.dvbern.ch/dockerhub/library/postgres:11-alpine
    networks:
      - kibon-exchange
    ports:
      - "${DB_PORT}:5432"
    environment:
      TZ: "Europe/Zurich"
      POSTGRES_USER: ${PG_EXCHANGE_SERVICE_USER}
      POSTGRES_PASSWORD: ${PG_EXCHANGE_SERVICE_PW}
      POSTGRES_DB: ${PG_EXCHANGE_SERVICE_DB}

  keycloak:
    image: docker-registry.dvbern.ch/dockerhub/jboss/keycloak:${KEYCLOAK_VERSION}
    networks:
      - kibon-exchange
    ports:
      - "8180:8080"
      - "8543:8443"
    volumes:
      - ${CONF_DIR}/keycloak/kibon_realm.json:/tmp/kibon_realm.json
      - ${CONF_DIR}/keycloak/set-secrets.sh:/opt/jboss/startup-scripts/set-secrets.sh
    command: "-Dkeycloak.profile.feature.upload_scripts=enabled"
    environment:
      TZ: "Europe/Zurich"
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_FRONTEND_URL: ${KEYCLOAK_FRONTEND_URL}
      # we map the realm configuration to /tmp/kibon_realm.json, but set-secrets.sh adds the secrets in
      # /opt/jboss/kibon_realm.json, because otherwise we modifiy the input file, e.g. the file on the localhost
      KEYCLOAK_IMPORT: "/opt/jboss/kibon_realm.json"
      KITADMIN_SECRET: ${KITADMIN_SECRET}
      KIBON_EXCHANGE_SERVICE_SECRET: ${KIBON_EXCHANGE_SERVICE_SECRET}

networks:
  kibon-exchange:
