---
info:
  title: kiBon Exchange Service API
  version: "1.0"

components:
  securitySchemes:
    OAuth2:
      type: oauth2
      description: This API uses OAuth 2 with the client credentials grant flow.
      flows:
        clientCredentials:
          tokenUrl: /../auth/realms/kibon/protocol/openid-connect/token
          scopes:
            user: Gestattet Zugriff auf die APIs für Verfügungen und Platzbestätigungen
            familyportal: Erlaubt den Zugriff auf Institutionen für das Familienportal des Kanton Bern.
            tagesschule: Gestattet Zugriff auf die APIs für Tagesschulen
  responses:
    Unauthorized:
      description: Die Zugriffsdaten sind nicht gültig
      content:
        text/plain: { }
    Forbidden:
      description: Der Zugriff wurde verweigert
      content:
        text/plain: { }
    NotFound:
      description: Die angeforderte Ressource existiert nicht
      content:
        text/plain: { }
    ServerError:
      description: Interner Server Fehler
      content:
        text/plain: { }
