version: '2'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.1
    # make sure to match the UID:GID of the host (due to volume binding)
    user: "1000"
    networks:
      - kibon_exchange_backbone
    ports:
      - "2181:2181"
    volumes:
      - ./zookeeper/data:/var/lib/zookeeper/data
      - ./zookeeper/log:/var/lib/zookeeper/log
      - ./zookeeper/jvmlogs:/var/log/kafka
    environment:
      TZ: "Europe/Zurich"
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:5.3.1
    # make sure to match the UID:GID of the host (due to volume binding)
    user: "1000"
    networks:
      - kibon_exchange_backbone
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    volumes:
      - ./kafka/data:/var/lib/kafka/data
      - ./kafka/jvmlogs:/var/log/kafka
    environment:
      TZ: "Europe/Zurich"
      KAFKA_LOG_RETENTION_HOURS: -1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://${KAFKA_ADDR}:9092
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  schema-registry:
    image: confluentinc/cp-schema-registry:5.3.1
    hostname: schema-registry
    networks:
      - kibon_exchange_backbone
    depends_on:
      - zookeeper
      - kafka
    ports:
      - "8081:8081"
    environment:
      TZ: "Europe/Zurich"
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'
      SCHEMA_REGISTRY_AVRO_COMPATIBILITY_LEVEL: 'full_transitive'
      SCHEMA_REGISTRY_DEBUG: 'true'

  keycloak:
    # Unfortunatley, scriptimport does not work with keyclaok > 7.0.0 - https://issues.redhat.com/browse/KEYCLOAK-12198
    # use keycloak 7.0.0 to initialise the database, then upgrade to 10.0.0
    image: quay.io/keycloak/keycloak:10.0.0
    networks:
      - kibon_exchange_backbone
    volumes:
      - ./keycloak/kibon_realm.json:/tmp/kibon_realm.json:ro
      - ./keycloak/set-secrets.sh:/opt/jboss/startup-scripts/set-secrets.sh:ro
    environment:
      TZ: "Europe/Zurich"
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      DB_VENDOR: "postgres"
      DB_ADDR: ${DB_ADDR}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: "keycloak"
      DB_USER: ${KEYCLOAK_DB_USER}
      DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      PROXY_ADDRESS_FORWARDING: "true"
      # should be enabled on productive systems
      #      KEYCLOAK_ALWAYS_HTTPS: "true"
      KEYCLOAK_IMPORT: "/opt/jboss/kibon_realm.json"
      KITADMIN_SECRET: ${KITADMIN_SECRET}
      KIBON_EXCHANGE_SERVICE_SECRET: ${KIBON_EXCHANGE_SERVICE_SECRET}

  service:
    # activated, because the service crashes at boot when keycloak is not available https://github.com/quarkusio/quarkus/issues/4619
    restart: on-failure
    image: docker.dvbern.ch/kibon/exchange-service:${VERSION}
    networks:
      - kibon_exchange_backbone
    depends_on:
      - kafka
      - keycloak
    volumes:
      - ./service/certs/key.pem:/key.pem:ro
      - ./service/certs/cert.pem:/cert.pem:ro
    environment:
      TZ: "Europe/Zurich"
      KAFKA_BOOTSTRAP_SERVERS: "${KAFKA_ADDR}:9092"
      QUARKUS_DATASOURCE_URL: "jdbc:postgresql://${DB_ADDR}:${DB_PORT}/kibon-exchange"
      QUARKUS_DATASOURCE_PASSWORD: ${QUARKUS_DATASOURCE_PASSWORD}
      # this requires a trusted certificate: change to public URL passing through netscaler
      QUARKUS_OIDC_AUTH_SERVER_URL: "http://keycloak:8080/auth/realms/kibon"
      QUARKUS_OIDC_CREDENTIALS_SECRET: ${KIBON_EXCHANGE_SERVICE_SECRET}

  nginx:
    image: docker.dvbern.ch/kibon/exchange-nginx:${VERSION}
    networks:
      - kibon_exchange_backbone
    depends_on:
      - service
    ports:
      - "443:443"
    volumes:
      - ./nginx/certs/key.pem:/etc/nginx/certs/key.pem:ro
      - ./nginx/certs/cert.pem:/etc/nginx/certs/cert.pem:ro

networks:
  kibon_exchange_backbone:
