version: '2'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      TZ: "Europe/Zurich"

  kafka:
    image: confluentinc/cp-kafka:5.3.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      TZ: "Europe/Zurich"
      KAFKA_LOG_DIRS: "/tmp/logs"
      KAFKA_LOG_RETENTION_HOURS: -1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  schema-registry:
    image: confluentinc/cp-schema-registry:5.3.1
    hostname: schema-registry
    depends_on:
      - zookeeper
      - kafka
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'
      SCHEMA_REGISTRY_AVRO_COMPATIBILITY_LEVEL: 'forward_transitive'

  db:
    image: postgres:11-alpine
    ports:
      - "15432:5432"
    environment:
      TZ: "Europe/Zurich"
      POSTGRES_USER: kibonExchange
      POSTGRES_PASSWORD: kibonExchange
      POSTGRES_DB: kibon-exchange

  keycloak:
    image: quay.io/keycloak/keycloak:7.0.0
    ports:
      - "8180:8080"
      - "8543:8443"
    volumes:
      - ./keycloak/kibon_realm.json:/tmp/kibon_realm.json
      - ./keycloak/set-secrets.sh:/opt/jboss/startup-scripts/set-secrets.sh
    environment:
      TZ: "Europe/Zurich"
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      # we map the realm configuration to /tmp/kibon_realm.json, but set-secrets.sh adds the secrets in
      # /opt/jboss/kibon_realm.json, because otherwise we modifiy the input file, e.g. the file on the localhost
      KEYCLOAK_IMPORT: "/opt/jboss/kibon_realm.json"
      KITADMIN_SECRET: "657d6aef-bdc3-40e9-9992-024810d2b24b"
      KIBON_EXCHANGE_SERVICE_SECRET: "4cf4f780-3856-46ee-850d-f07789675a33"
