version: '2'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.1
    user: "1000"
    networks:
      - kibon_exchange_backbone
    ports:
      - "2181:2181"
    volumes:
      - ./zookeeper/data:/var/lib/zookeeper/data
      - ./zookeeper/log:/var/lib/zookeeper/log
      - ./zookeeper/jvmlogs:/var/log/kafka
    environment:
      TZ: "Europe/Zurich"
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:5.5.1
    # make sure to match the UID:GID of the host (due to volume binding)
    user: "1000"
    networks:
      - kibon_exchange_backbone
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    volumes:
      - ./kafka/data:/var/lib/kafka/data
      - ./kafka/jvmlogs:/var/log/kafka
    environment:
      TZ: "Europe/Zurich"
      KAFKA_LOG_RETENTION_HOURS: -1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://${KAFKA_ADDR}:9092
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  schema-registry:
    image: confluentinc/cp-schema-registry:5.5.1
    hostname: schema-registry
    networks:
      - kibon_exchange_backbone
    depends_on:
      - zookeeper
      - kafka
    ports:
      - "8081:8081"
    environment:
      TZ: "Europe/Zurich"
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'
      SCHEMA_REGISTRY_AVRO_COMPATIBILITY_LEVEL: 'full_transitive'
      SCHEMA_REGISTRY_DEBUG: 'true'

  keycloak:
    image: quay.io/keycloak/keycloak:7.0.0
    ports:
      - "8180:8080"
    networks:
      - kibon_exchange_backbone
    volumes:
      - ./keycloak/kibon_realm.json:/tmp/kibon_realm.json:ro
      - ./keycloak/set-secrets.sh:/opt/jboss/startup-scripts/set-secrets.sh:ro
    environment:
      TZ: "Europe/Zurich"
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      DB_VENDOR: "postgres"
      DB_ADDR: ${DB_ADDR}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: "keycloak"
      DB_USER: ${KEYCLOAK_DB_USER}
      DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      PROXY_ADDRESS_FORWARDING: "true"
      # should be enabled on productive systems
      #      KEYCLOAK_ALWAYS_HTTPS: "true"
      KEYCLOAK_IMPORT: "/opt/jboss/kibon_realm.json"
      KITADMIN_SECRET: ${KITADMIN_SECRET}
      KIBON_EXCHANGE_SERVICE_SECRET: ${KIBON_EXCHANGE_SERVICE_SECRET}

networks:
  kibon_exchange_backbone:
